### PR TITLE
feat: Adds measures from BRICR and removes duplicates from OS-Common-Measures

### PR DESCRIPTION
**Pull request by corymosiman12**

### CODE REVIEW

**Review by DavidGoldwasser — APPROVED** [review]

**Comment by DavidGoldwasser** [comment]
@corymosiman12 there are now 5 load errors in CI for this. Those will have to be addressed before this can be merged.

**Comment by DavidGoldwasser** [comment]
Note that https://github.com/NREL/openstudio-ee-gem/pull/12 should get merged to develop before this one is. The one there is setup with latest extension and standards gem and all test passed. Maybe you should merge that branch into this, or wait for @nllong to merge that and just update this branch from develop.

**Comment by nllong** [comment]
@corymosiman12 -- I think `develop` is ready to be merged up. I am slightly concerned that this is now aligned with the upcoming OS 3.1 release. Do we foresee any compatibility issues between OS 3.0.x and 3.1?

**Comment by corymosiman12** [comment]
@nllong removing this PR in favor of a patch to 0.2.0 see #13

**Pull request closed without merging**
