### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by DavidGoldwasser**

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@mdahlhausen there is one test failing in nze_hvac with this error, was there a change in standards this could be related to or maybe OpenStudio model API in 3.2?

Failure: test_office_radiant_doas(Minitest::Result) [/srv/jenkins/git/openstudio-ee-gem/PR-28/1/.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.12/lib/openstudio-standards/prototypes/common/objects/Prototype.radiant_system_controls.rb:28]: NoMethodError: undefined method `to_CoilCoolingLowTempRadiantVarFlow' for #<OpenStudio::Model::OptionalHVACComponent:0x000055db564604b0>

**Comment by DavidGoldwasser** [comment]
@mdahlhausen this seems very familiar and I think we fixed it, might be similar issue I'm having to calibration gem with how CI is choose ext and standards gem.

**Comment by DavidGoldwasser** [comment]
@nllong another measure gem repo ready

**Review by kflemin — APPROVED** [review]

**Review by nllong — APPROVED** [review]
looks awesome!

**Pull request merged**
